### PR TITLE
Add the corresponding commit id for all the README files

### PR DESCRIPTION
**Pull request by mudongliang**

### CODE REVIEW

**Comment by mudongliang** [comment]
@xinqiu how do you think about this PR?

**Comment by xinqiu** [comment]
It's OK, just a bit of trouble.But we can try it.

**Comment by mudongliang** [comment]
We need to verify the commit id for all the files. It is a longterm job.

**Comment by mudongliang** [comment]
If you agree with this idea, please merge this PR and we will try to maintain those information.

**Comment by hao-lee** [comment]
> We need to verify the commit id for all the files. It is a longterm job.

Yeah. We need to find out the correct commit id of English version for each translated file. This is indeed not easy.

**Pull request merged**
